### ISSUE TITLE
Rounded bubble with "/" as content

### ISSUE THREAD

**Issue by big-r81** [kevinpt/syntrax#2]
Hi,

is it possible to create a rounded bubble with a slash ("/") as text?

Cheers,
Ronny

**Comment by kevinpt** [comment]
You can change the trigger for bubble styling with a custom style. Get the defaults first with the --get-style option. Then edit the "pattern" regex rules in the syntrax.ini file. You can swap the patterns used for the "[box]" and "[bubble]" sections to make forward slashes activate the bubble outline.

Then run Syntrax in the same directory as the custom ini or use the --style option to point it at the correct path.

https://kevinpt.github.io/syntrax/#node-styles

**Comment by big-r81** [comment]
Okay, thanks for your hints.

I would like to use two slashes // as trigger.
So i used:
```
pattern='^//' or
pattern='^/{2}'
```

Then i get the following output for this test file
```
line('//box')
```

output:
![test](https://user-images.githubusercontent.com/9985963/31850737-fd4dfd42-b657-11e7-8b71-c280f01768a2.png)

Can i only use one char for different box types?

**Comment by big-r81** [comment]
Ok,

for my special case, i found out that i have to change ```text_mod```too!
```
text_mod = 'lambda txt: txt[2:]'
```
