### ISSUE TITLE
`gi` is an unsupported dependency

### ISSUE THREAD

**Issue by rawrgulmuffins** [kevinpt/syntrax#3]
# Problem Statement

I was attempting to use a separate library (`syntrax`) and ran into the problem that gi is still using the old print statement. This isn't a problem in the larger sense. Normally when I run into projects like this I write a pull request to port the dependency to python3. 

In this case, however, I discovered that `gi` isn't a supported package anymore and the last release was in 2014.

If you look at the [`gi` dependency on pypi](https://pypi.python.org/pypi/gi) you'll find that it has a home page listed. If you look [look at the project home page](https://github.com/inconditus/gi) you'll see that the page is down and that `inconditus` doesn't have it listed under their repositories anymore.

I would suggest moving to a new dependency if possible. I don't know enough about this space right now to suggest an alternative but if you'd like help I can find the time later to look into it.

# Error in Question

```
syntrax
Traceback (most recent call last):
  File "/Users/alexlord/.virtualenvs/presentations/lib/python3.6/site-packages/syntrax.py", line 20, in <module>
    import pango
ModuleNotFoundError: No module named 'pango'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/alexlord/.virtualenvs/presentations/bin/syntrax", line 7, in <module>
    from syntrax import main
  File "/Users/alexlord/.virtualenvs/presentations/lib/python3.6/site-packages/syntrax.py", line 24, in <module>
    from gi.repository import Pango as pango
  File "/Users/alexlord/.virtualenvs/presentations/lib/python3.6/site-packages/gi/__init__.py", line 39
    print url
            ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(t url)?
```

**Comment by kevinpt** [comment]
I'm not sure there the bad print is coming from. It looks like other people are having a similar issue but I can't see a Py2 print statement anywhere.

This is from my `gi/__init__.py` at line 39:

```python
# we can't have pygobject 2 loaded at the same time we load the internal _gobject
if 'gobject' in sys.modules:
    raise ImportError(_static_binding_error)
```

This is on an old Debian 8 install. The file looks unchanged in [the latest code](https://github.com/GNOME/pygobject/blob/master/gi/__init__.py).

**Comment by rawrgulmuffins** [comment]
# Steps To Reproduce
I did this on a OSX 10.13.3 system

```
brew install pango
virtualenvwrapper --python=$(which python3) syntrax3
workon syntrax3
pip install pycairo
pip install gobject
pip install gi
```

These steps reproduce the same stack trace.
